"""
Django settings for billing project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(a7i-b94@@_j604q3q@yzty$g98&wv)^p2y$#=$5u+a1fmw@xz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'longer_username',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'accounts',
    'packages',
    'payments',
    'search',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'billing.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'billing.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'radius',
        'USER': 'radius',
        'PASSWORD': 'radpass',
        'HOST': '127.0.0.1',
        'PORT': '3306'
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'GMT'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

STATIC_ROOT = os.path.join(BASE_DIR, "static_live")

LOGIN_URL = 'accounts:login'

LOGIN_REDIRECT_URL = 'index'

DEFAULT_FROM_EMAIL = 'test@example.com'

SITE_ID = 1

EMAIL_HOST = '74.55.86.74'

EMAIL_PORT = 25

EMAIL_HOST_USER = 'deone'

EMAIL_HOST_PASSWORD = '@dune369'

# VMS
VMS_URL = "http://localhost:3000/vouchers/"

VOUCHER_STUB_INSERT_URL = VMS_URL + "insert/"

VOUCHER_STUB_DELETE_URL = VMS_URL + "delete/"

VOUCHER_REDEEM_URL = VMS_URL + "redeem/"

VOUCHER_INVALIDATE_URL = VMS_URL + "invalidate/"

VOUCHER_SELL_URL = VMS_URL + "sell/"

SUCCESS_URL = "http://localhost:8000/success/"

# More settings

# Speed variants 
STARTER = '0.128'
BASIC = '0.256'
REGULAR = '0.512'
LITE = '1'
DELUXE = '1.5'
PREMIERE = '2'
ULTRA = '3'
SUPREME = '4'

# Speed names
SPEED_NAME_MAP = {
    STARTER: '128Kbps Starter',
    BASIC: '256Kbps Basic',
    REGULAR: '512Kbps Regular',
    LITE: '1Mbps Lite',
    DELUXE: '1.5Mbps Deluxe',
    PREMIERE: '2Mbps Premiere',
    ULTRA: '3Mbps Ultra',
    SUPREME: '4Mbps Supreme'
}

SPEED_CHOICES = (
    (STARTER, SPEED_NAME_MAP[STARTER]),
    (BASIC, SPEED_NAME_MAP[BASIC]),
    (REGULAR, SPEED_NAME_MAP[REGULAR]),
    (LITE, SPEED_NAME_MAP[LITE]),
    (DELUXE, SPEED_NAME_MAP[DELUXE]),
    (PREMIERE, SPEED_NAME_MAP[PREMIERE]),
    (ULTRA, SPEED_NAME_MAP[ULTRA]),
    (SUPREME, SPEED_NAME_MAP[SUPREME]),
)

# Volume variants
TEST = '0.01'
ONE = '1'
THREE = '3'
FIVE = '5'
EIGHT = '8'
TEN = '10'
TWELVE = '12'
FIFTEEN = '15'
TWENTY = '20'
TWENTY_FIVE = '25'
UNLTD = 'Unlimited'

# Volume names
VOLUME_NAME_MAP = {
    TEST: '0.0005GB',
    ONE: '1GB',
    THREE: '3GB',
    FIVE: '5GB',
    EIGHT: '8GB',
    TEN: '10GB',
    TWELVE: '12GB',
    FIFTEEN: '15GB',
    TWENTY: '20GB',
    TWENTY_FIVE: '25GB',
    UNLTD: 'Unlimited'
}

VOLUME_CHOICES = (
    (TEST, VOLUME_NAME_MAP[TEST]),
    (ONE, VOLUME_NAME_MAP[ONE]),
    (THREE, VOLUME_NAME_MAP[THREE]),
    (FIVE, VOLUME_NAME_MAP[FIVE]),
    (EIGHT, VOLUME_NAME_MAP[EIGHT]),
    (TEN, VOLUME_NAME_MAP[TEN]),
    (TWELVE, VOLUME_NAME_MAP[TWELVE]),
    (FIFTEEN, VOLUME_NAME_MAP[FIFTEEN]),
    (TWENTY, VOLUME_NAME_MAP[TWENTY]),
    (TWENTY_FIVE, VOLUME_NAME_MAP[TWENTY_FIVE]),
    (UNLTD, VOLUME_NAME_MAP[UNLTD]),
)

DAILY = 'Daily'
WEEKLY = 'Weekly'
MONTHLY = 'Monthly'

PACKAGE_TYPES = (
    (DAILY, 'Daily'),
    (WEEKLY, 'Weekly'),
    (MONTHLY, 'Monthly'),
)

PACKAGE_TYPES_HOURS_MAP = {
    DAILY: 1 * 24,
    WEEKLY: 7 * 24,
    MONTHLY: 30 * 24
}

MAX_FILE_LENGTH = 30

# Set this to False to test BulkUserUploadForm.clean()
# EXCEED_MAX_USER_COUNT = True
EXCEED_MAX_USER_COUNT = False

# Payments
STORE_NAME = 'Spectra Wireless'

PAYMENT_DESCRIPTION = 'Package Purchase'
PAYMENT_MASTER_KEY = 'cef70167-7dec-458e-b5bf-1befb4196565'

# - Test API
PAYMENT_TEST_URL = 'https://app.mpowerpayments.com/sandbox-api/v1/checkout-invoice/create'
PAYMENT_TEST_PRIVATE_KEY = 'test_private_-TBbZrbdchpR6RZ9aB6g9Hx6-wk'
